### ISSUE TITLE
Create and release a gem

### ISSUE THREAD

**Issue by boncey** [boncey/ruby-podcast#2]
Figure out how to create a gem then get it released on rubygems or somewhere like that.

**Comment by shadowbq** [comment]
Can you please release this gem.. it is very easy.
```
user@test:~/sandbox/ruby-podcast# rake -T
rake build          # Build ruby-podcast-0.0.6.gem into the pkg directory
rake default        # Run tests
rake install        # Build and install ruby-podcast-0.0.6.gem into system ...
rake install:local  # Build and install ruby-podcast-0.0.6.gem into system ...
rake release        # Create tag v0.0.6 and build and push ruby-podcast-0.0...
rake test           # Run tests
```

Test seem fairly ok..
```
user@test:~/sandbox/ruby-podcast# rake test
Run options: 

# Running tests:

Skipping test/bad.mp3 as it has a problem: Mp3InfoEOFError
.Skipping test/bad.mp3 as it has a problem: Mp3InfoEOFError
...Skipping bad.mp3 as it has a problem: Mp3InfoEOFError
.

Finished tests in 0.069935s, 71.4949 tests/s, 100.0929 assertions/s.

5 tests, 7 assertions, 0 failures, 0 errors, 0 skips
```

Gem builds ok.
```
user@test:~/sandbox/ruby-podcast# gem build podcast.gemspec 
  Successfully built RubyGem
  Name: ruby-podcast
  Version: 0.0.6
  File: ruby-podcast-0.0.6.gem
user@test:~/sandbox/ruby-podcast# gem install ruby-podcast-0.0.6.gem 
Fetching: ruby-mp3info-0.8.7.gem (100%)
Successfully installed ruby-mp3info-0.8.7
Successfully installed ruby-podcast-0.0.6
2 gems installed

Installing ri documentation for ruby-mp3info-0.8.7...
Installing ri documentation for ruby-podcast-0.0.6...
Installing RDoc documentation for ruby-mp3info-0.8.7...
Installing RDoc documentation for ruby-podcast-0.0.6...
```
use the name space 'ruby-podcast' as defined in gem already.. no-change needed.

Gem namespace is empty:
https://rubygems.org/search?utf8=%E2%9C%93&query=ruby-podcast

Publish the Gem way:
http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

To begin, you’ll need to create an account on RubyGems.org. Visit the sign up page and supply an email address that you control, a handle (username) and a password.

```
$ gem push squid-utils-0.1.0.gem
```

Or publish onto rubygems and github with tags at the same time..

```
rake release        # Create tag v0.0.6 and build and push ruby-podcast-0.0...
```

**Comment by boncey** [comment]
Thanks for looking into this.

The previous owners refused to let me release it (they owned the 'ruby-podcast' project on RubyGems) but it looks like they've gone now so I can finally release it. :-)

**Comment by boncey** [comment]
Hmmm, I just checked my emails again and it seems that the old project is still around - https://rubygems.org/gems/podcast

I can try releasing under the new name as you suggested.

**Comment by boncey** [comment]
It's released! https://rubygems.org/gems/ruby-podcast

Thanks for outlining all the steps.
If you could give it a quick once over I can update the README file and close this issue.

Thanks again, Darren.

**Comment by shadowbq** [comment]
thanks.. I'll pass some PR's if needed.
